### PR TITLE
#132 Removed puzzle

### PR DESCRIPTION
**Pull request by carlosmiranda**
See discussion on #132 for more details.

### CODE REVIEW

**Comment by karato** [comment]
Thanks, let me find someone who can review this pull request

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled paid, thanks, added **16 mins** to your account, payment `54285594`, 17 hours and 46 mins was spent

extra minutes for review comments (c=1)

+16 added to your rating, current score is: [+2294](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
