### PR TITLE
#243 added visibility to documents

### PR DESCRIPTION
**Pull request by krzyk**
#243

I've refactored `Doc` to have a separate class for attributes and implemented visibility modifier there. I've implemented `MkAttributes` and added todo for `AwsAttributes` implementation. Added todo for modification of the attribute from the web page, and for displaying the attribute state.

### CODE REVIEW

**Comment by karato** [comment]
@krzyk Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@krzyk there are some merge conflicts, could you please resolve them?

**Comment by krzyk** [comment]
@darkled I've merged master, please check again

**Comment by asaen** [comment]
@krzyk thank you

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled done, I added **18 mins** in payment `56392868`, 54 hours and 53 mins spent to complete this; extra minutes for review comments (c=3); +18 to your rating, your total score is [+2165](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
