### PR TITLE
#160 added tests for special character file names

### PR DESCRIPTION
**Pull request by krzyk**
#160

I've added tests for the errors when trying to read or delete a file with special characters (ones that are encoded in HTTP) and added a todo to enable them when yegor256/takes#126 is fixed and released in new takes version.

### CODE REVIEW

**Comment by karato** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge this

**Comment by karato** [comment]
@darkled Thank you, I have added **16 mins** to your account in payment/transaction "`55000188`", time consumed: 48 hours and 5 mins

extra minutes for review comments (c=1)

+16 added to your rating, current score is: [+2382](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
