### PR TITLE
#12 Let's introduce web framework

### PR DESCRIPTION
**Pull request by pinaf**
#12 Let's introduce web framework

### CODE REVIEW

**Comment by karato** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@krzyk do this review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by ggajos** [comment]
@rultor merge

**Comment by ggajos** [comment]
@pinaf looks like cobertura is complaining

**Comment by pinaf** [comment]
@ggajos I had no idea we had cobertura here already. I'll fix it but please take a look at #42

**Comment by pinaf** [comment]
@ggajos when running maven locally cobertura didn't complain but I added a new test anyway. please try again.

**Comment by pinaf** [comment]
@ggajos still complaining..no idea what else to test. `Launch` only has 2 methods both of which are tested.

**Comment by krzyk** [comment]
@pinaf maybe resource close is not tested (when the resource can't be closed)? Have you tried `mvn clean install cobertura:cobertura` and check the report generated in `target/site/cobertura/`  (I'm not sure about directory, but it definatelly has `index.html` file)

**Comment by pinaf** [comment]
@krzyk which resource?

**Comment by krzyk** [comment]
@pinaf oh, sorry, it was in the code that you removed, so that's not it, best to check cobertura report and see what it really wants

**Comment by pinaf** [comment]
had to change some stuff around :( let's see what travis says now.

**Comment by pinaf** [comment]
@ggajos @krzyk seems like it is good now. please take a look.

**Comment by ggajos** [comment]
@pinaf thank you, looks like it's ok now

**Comment by ggajos** [comment]
let see what rultor say

**Comment by ggajos** [comment]
@rultor merge

**Comment by pinaf** [comment]
@ggajos I added a puzzle also.

**Comment by pinaf** [comment]
@ggajos network issues?

**Comment by ggajos** [comment]
@pinaf looks like

**Comment by ggajos** [comment]
@rultor merge

**Comment by karato** [comment]
@rultor deploy

**Comment by karato** [comment]
@krzyk thank you, added **15 mins** to your acc, payment num is `52905074`. +15 added to your rating, current score is: [+4815](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
