### PR TITLE
#170 Raised Cobertura Total Line Rate

### PR DESCRIPTION
**Pull request by carlosmiranda**
See #170. I raised the line rate as instructed, and Cobertura successfully passed - I didn't have to add to or modify any existing tests.

### CODE REVIEW

**Comment by karato** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled **16 mins** sent to your balance (ID `55065443`), many thanks! It took 17 hours and 28 mins.... extra minutes for review comments (c=1)... +16 added to your rating, at the moment it is: [+2503](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
