### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
updated.

### CODE REVIEW

**Comment by karato** [comment]
Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled Much obliged! I have added **16 mins** to your account in payment "54253532", 17 hours and 11 mins spent. extra minutes for review comments (c=1). +16 added to your rating, current score is: [+2260](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
