### PR TITLE
#151 can't upload files in batches

### PR DESCRIPTION
**Pull request by pinaf**
For #151 
- changed `README.md`
- added `Batch` interface
- added `MkBatch` class with unit test
- added puzzle to `TkWrite`

### CODE REVIEW

**Comment by karato** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@maurezen review it

**Comment by maurezen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge this

**Comment by karato** [comment]
@maurezen thank you, added **16 mins** to your acc, payment num is `54971952`, 24 hours and 5 mins spent in total to complete... review comments (c=1) added as a bonus... +16 added to your rating, at the moment it is: [+1297](http://www.netbout.com/b/35102?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
