### PR TITLE
#104: document fix for firefoxi

### PR DESCRIPTION
**Pull request by ggajos**
for #104 

why this is working: http://ukchill.com/technology/generating-html5-using-xslt/

### CODE REVIEW

**Comment by karato** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@krzyk do this review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@ggajos I don't see why you disabled that tests. They both work fine for me after your changes... are you sure they fail?

**Comment by yegor256** [comment]
@ggajos can you show their failure stacktrace?

**Comment by yegor256** [comment]
@ggajos I think I know what the problem is. You should remove this line from `layout.xsl` and put it into `docs.xsl` and `home.xsl`.

**Comment by yegor256** [comment]
@ggajos see what I mean: https://github.com/yegor256/rultor/commit/e6272223418d451044cbfbaf6839c77ae4a3b9f9

**Comment by yegor256** [comment]
@ggajos oops, I made changes into master in a0e9e96572f42eddffebd035d8b1607353bb9b2e Looks like you can just close this pull request and we'll close the ticket

**Comment by ggajos** [comment]
@yegor256 thanks

**Comment by karato** [comment]
@krzyk **16 mins** added to your account (payment number `54202140`), many thanks for your contribution! 30 hours and 46 mins spent here.; you're getting extra minutes here (c=1); +16 added to your rating, current score is: [+5339](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
