### PR TITLE
#21 Logo link fixed

### PR DESCRIPTION
**Pull request by longtimeago**

### CODE REVIEW

**Comment by longtimeago** [comment]
@karato please, find a reviewer

**Comment by karato** [comment]
I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@rultor merge

**Comment by ggajos** [comment]
@rultor merge please

**Comment by karato** [comment]
@darkled Thanks a lot, I just topped your account for **16 mins**, transaction ID `52513008`; extra minutes for review comments (c=1); +16 to your rating, your total score is [+1583](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
