### PR TITLE
#216 login page

### PR DESCRIPTION
**Pull request by yegor256**
see #216 login page modified

### CODE REVIEW

**Comment by karato** [comment]
@yegor256 Thanks, let me find someone who can review this pull request

**Comment by karato** [comment]
@longtimeago do this review

**Comment by karato** [comment]
@longtimeago we're on pause in the project, please stop working with this, until further information

**Comment by yegor256** [comment]
@rultor merge it

**Comment by karato** [comment]
@longtimeago I don't see any messages from you above, not sure if there was actual contribution (correct me if I'm wrong)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
