### PR TITLE
#255 set visibility functionality

### PR DESCRIPTION
**Pull request by pinaf**
For #255
- moved `TkSetVisibilityTest` to correct package
- added unit test + puzzle for missing `MkAttribute` functionality
- wired `set-visibility` functionality

### CODE REVIEW

**Comment by karato** [comment]
@pinaf Thanks, let me find someone who can review this pull request

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled thank you, added **16 mins** to your acc, payment num is `57265758`, 41 hours and 32 mins spent in total to complete. extra minutes for review comments (c=1). added +16 to your rating, now it is equal to [+1943](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
