### PR TITLE
#102: added pdd & size

### PR DESCRIPTION
**Pull request by ggajos**
for #102

it's a second PR

### CODE REVIEW

**Comment by karato** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@alevohin review it

**Comment by alevohin** [comment]
@rultor merge @ggajos thank you!

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@ggajos you got the idea!

**Comment by ggajos** [comment]
@yegor256 hmm, it's weird, pdd is long enought but rultor is reading only first line of it; inlined pdd; maybe it helps

**Comment by alevohin** [comment]
@ggajos could you check issues for PDD about this problem or create new one?

**Comment by ggajos** [comment]
@alevohin yes, I inlined this, so now entire pdd is in one line, maybe it help; it's already commited. It looks like it was counting only first line of comment.

**Comment by alevohin** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by karato** [comment]
@alevohin **18 mins** was added to your account, many thanks for your contribution! The task took 54251533.

you're getting extra minutes here (c=3)

added +18 to your rating, now it is equal to [+2055](http://www.netbout.com/b/35105?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
