### PR TITLE
#46: updated rultor image + forced jdk8

### PR DESCRIPTION
**Pull request by ggajos**
for #46

### CODE REVIEW

**Comment by karato** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@longtimeago review it

**Comment by longtimeago** [comment]
@ggajos there are lot's of failed tests

**Comment by ggajos** [comment]
I see that @carlosmiranda have already working solution in #47. Let's skip this one.

**Comment by karato** [comment]
@longtimeago Thanks so much! Your account was topped up for **16 mins** (transaction ID is `52964578`)

you're getting extra minutes here (c=1)

+16 added to your rating, current score is: [+2826](http://www.netbout.com/b/35024?open=rating)

**Pull request closed without merging**
