### PR TITLE
#274 fix date

### PR DESCRIPTION
**Pull request by dmzaytsev**
#274

### CODE REVIEW

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by k0r** [comment]
@dmzaytsev `Travis CI build is in progress`

**Comment by dmzaytsev** [comment]
@k0r rultor makes build before merge
rultor doesn't merge if the build fail

**Comment by yegor256** [comment]
@k0r keep in mind that Travis is only supplementary for us. Rultor is a much stronger protection mechanism. Even if Travis says that everything is fine, we don't trust this information entirely. All merges should go through Rultor.

**Comment by k0r** [comment]
@yegor256 merge confirmations and reviews often take more time than it should, that's why I've been manually merging PRs.

**Comment by dmzaytsev** [comment]
@yegor256 let's release it?

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.32`

**Comment by k0r** [comment]
@dmzaytsev many thanks.

**Comment by dmzaytsev** [comment]
@yegor256 @k0r it works

**Comment by k0r** [comment]
@dmzaytsev bit.ly links are all the same.

**Comment by yegor256** [comment]
@dmzaytsev @k0r please remember that we are using one issue per problem. Every time we see a bug, a new issue has to be created, a new performer assigned, etc.

**Pull request merged**
