### PR TITLE
Update home.xsl

### PR DESCRIPTION
**Pull request by ghost**
updated.

### CODE REVIEW

**Comment by karato** [comment]
Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@krzyk review it

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@rultor deploy

**Comment by karato** [comment]
@krzyk thanks, paid, **15 mins** to your account, payment ID is `53802502`. +15 added to your rating, at the moment it is: [+5172](http://www.netbout.com/b/35035?open=rating)

**Pull request merged**
