### PR TITLE
#31: added put operation

### PR DESCRIPTION
**Pull request by ggajos**
for #31

### CODE REVIEW

**Comment by karato** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@ggajos looks nice, thanks

**Comment by asaen** [comment]
@rultor merge

**Comment by ggajos** [comment]
@rultor merge please

**Comment by asaen** [comment]
@ggajos it looks like there are some conflicts, please merge with master

**Comment by ggajos** [comment]
@rultor merge please

**Comment by karato** [comment]
@darkled thank you, added **17 mins** to your acc, payment num is `52815751`

you're getting extra minutes here (c=2)

+17 to your rating, your total score is [+1661](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
