### PR TITLE
#18 Java 8 set as minimal version

### PR DESCRIPTION
**Pull request by asaen**

### CODE REVIEW

**Comment by karato** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@longtimeago review it

**Comment by longtimeago** [comment]
@karato You need to modify `.travis.yml` as well.
By default it builds with jdk7.
Add following for java8

```
jdk:
  - oraclejdk8
```

**Comment by asaen** [comment]
@longtimeago fixed, thank you

**Comment by longtimeago** [comment]
@darkled have you tried to run the build on java8?

**Comment by asaen** [comment]
@longtimeago yes, sure, I have `1.8.0_31`. Do you have problems with it?

```
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by longtimeago** [comment]
@darkled travis hangs the build

**Comment by longtimeago** [comment]
@darkled win/linux?
I have the same issue locally, as travis.
Test just hangs for indefinite time

I'm on Ubuntu 14.04. Java 1.8.0_31

**Comment by asaen** [comment]
@longtimeago win 7

**Comment by asaen** [comment]
@longtimeago according to [this](http://stackoverflow.com/questions/22634644/java-hotspottm-64-bit-server-vm-warning-ignoring-option-maxpermsize) `MaxPermSize` was removed in java 8, maybe due to some implementation issues it leads to hanging.. Let's see what will happen after removing these options..

**Comment by longtimeago** [comment]
@darkled I don't think it will help ... jvm just ignore that param

**Comment by asaen** [comment]
@longtimeago you're right. I will try to investigate the reason.

**Comment by longtimeago** [comment]
@darkled any news?

**Comment by asaen** [comment]
@longtimeago it looks like I have some good news, please take a look once more.

**Comment by longtimeago** [comment]
@darkled that's great!

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by ggajos** [comment]
@rultor merge

**Comment by ggajos** [comment]
@longtimeago looks like another merge conflict, could you please merge?

**Comment by asaen** [comment]
@ggajos merged

**Comment by asaen** [comment]
@ggajos could you try to merge again?

**Comment by ggajos** [comment]
@rultor merge

**Comment by ggajos** [comment]
@darkled thanks

**Comment by ggajos** [comment]
hmm, can't access logs, let's try again

**Comment by ggajos** [comment]
@rultor merge

**Comment by asaen** [comment]
@ggajos it seems that rultor is working on a machine with java 7 and cannot compile 8 sources.

**Comment by asaen** [comment]
@ggajos I've created the issue about it #46

**Comment by asaen** [comment]
@karato it seems we have to wait for #46

**Comment by karato** [comment]
> @karato it seems we have to wait for #46 

@darkled sure, let's wait for #46

**Comment by ggajos** [comment]
@pinaf @longtimeago @darkled think there is no point in waiting for rultor to be compatibile. Let's downgrade minimum version to 7.

**Comment by asaen** [comment]
@ggajos agreed

**Comment by asaen** [comment]
@longtimeago @ggajos rolled back all changes, take a look once more please.

**Comment by asaen** [comment]
I think I mixed up something while resetting git commits, sorry, will create a new pull request, since I cannot reopen this one.

**Comment by ggajos** [comment]
@darkled no worries and thanks

**Comment by karato** [comment]
@longtimeago I added **23 mins** to your account, many thanks for working with the project!

you're getting extra minutes here (c=8)

added +23 to your rating, now it is equal to [+2804](http://www.netbout.com/b/35024?open=rating)

**Pull request closed without merging**
