### PR TITLE
231: large file upload fixed

### LINKED ISSUE #231: big files cause out-of-memory errors on Heroku

### PR DESCRIPTION
**Pull request by yegor256**
#231 upload of large files fixed, also done major refactoring of document processing takes

### CODE REVIEW

**Comment by yegor256** [comment]
@karato it's urgent

**Comment by karato** [comment]
@yegor256 Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
> @karato it's urgent

@yegor256 sure, thanks, I added "urgent" tag to it

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
