### PR TITLE
#241 fixed doc links

### PR DESCRIPTION
**Pull request by krzyk**
#241

Added test to check if correct document links exist in HTML and corrected the XML path to those links.

### CODE REVIEW

**Comment by karato** [comment]
@krzyk Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by krzyk** [comment]
@darkled @yegor256 I've merged master, please try again

**Comment by asaen** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled Thanks a lot, I just topped your account for **17 mins**, transaction ID `56771628`, total time was 47 hours and 44 mins; you're getting extra minutes here (c=2); added +17 to your rating, now it is equal to [+2079](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
