### PR TITLE
#157 Re-estimate project size

### PR DESCRIPTION
**Pull request by pinaf**
#157 Re-estimate project size

### CODE REVIEW

**Comment by karato** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@krzyk do this review

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by karato** [comment]
@krzyk thanks, I just added **16 mins** to your account, payment `54546576`, 21 hours and 56 mins spent; you're getting extra minutes here (c=1); +16 to your rating, your total score is [+5428](http://www.netbout.com/b/35035?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
