### PR TITLE
#188: takes 0.12

### PR DESCRIPTION
**Pull request by yegor256**
see #188 version of takes upgraded here

### CODE REVIEW

**Comment by karato** [comment]
Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@longtimeago review it

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by longtimeago** [comment]
@yegor256 humm ... travis build passes but rultor failed to compile ...

**Comment by yegor256** [comment]
@longtimeago that's why we need rultor! :)

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@rultor deploy

**Comment by karato** [comment]
@longtimeago Much obliged! I have added **17 mins** to your account in payment "55002453", 18 hours and 29 mins spent... extra minutes for review comments (c=2)... +17 to your rating, your total score is [+3831](http://www.netbout.com/b/35024?open=rating)

**Pull request merged**
