### PR TITLE
#89 Multipart upload/download

### PR DESCRIPTION
**Pull request by longtimeago**

### CODE REVIEW

**Comment by longtimeago** [comment]
@karato please find someone to review

**Comment by karato** [comment]
Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by karato** [comment]
@darkled paid, thanks, added **16 mins** to your account, payment `54118663`; you're getting extra minutes here (c=1); +16 to your rating, your total score is [+2159](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
