### PR TITLE
#30 Storage.java:45-47: Implement delete operation to remove...

### PR DESCRIPTION
**Pull request by pinaf**
#30 Storage.java:45-47: Implement delete operation to remove...

### CODE REVIEW

**Comment by karato** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@longtimeago do this review

**Comment by longtimeago** [comment]
@pinaf looks good, thank you!

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by pinaf** [comment]
@longtimeago thanks

**Comment by ggajos** [comment]
@rultor merge please

**Comment by karato** [comment]
@longtimeago Thanks for your contribution, **17 mins** was added to your account, payment ID is `52815784`. you're getting extra minutes here (c=2). +17 added to your rating, current score is: [+2573](http://www.netbout.com/b/35024?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
