### PR TITLE
#118 added interface and mock implementation for Account

### PR DESCRIPTION
**Pull request by krzyk**

### CODE REVIEW

**Comment by karato** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@longtimeago do this review

**Comment by longtimeago** [comment]
@krzyk looks pretty good, thanks!

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by karato** [comment]
@longtimeago thanks, paid, **17 mins** to your account, payment ID is `54586042`, task took 25 hours and 51 mins to complete

extra minutes for review comments (c=2)

+17 added to your rating, current score is: [+3717](http://www.netbout.com/b/35024?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
