### PR TITLE
#240 added content length

### PR DESCRIPTION
**Pull request by krzyk**
#240

Added content length for S3, to check that this is included in the metadata I used Mockito `Answer` interface. Few test methods had to be updated to take care of the changed interface of `Doc`.

### CODE REVIEW

**Comment by karato** [comment]
@krzyk I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled I just added **16 mins** to your account, many thanks for your contribution.. 56385961 spent here. extra minutes for review comments (c=1). added +16 to your rating, now it is equal to [+2147](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
