### PR TITLE
#79 Re-estimate project size

### PR DESCRIPTION
**Pull request by pinaf**
#79 Re-estimate project size

### CODE REVIEW

**Comment by karato** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@longtimeago do this review

**Comment by longtimeago** [comment]
@pinaf looks good

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by pinaf** [comment]
@longtimeago thanks

**Comment by pinaf** [comment]
@yegor256 do you mind confirming the merge?

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by pinaf** [comment]
@yegor256 thank you

**Comment by karato** [comment]
@rultor deploy

**Comment by karato** [comment]
@longtimeago thanks, I just added **17 mins** to your account, payment `53754112`

you're getting extra minutes here (c=2)

+17 added to your rating, at the moment it is: [+3160](http://www.netbout.com/b/35024?open=rating)

**Pull request merged**
