### PR TITLE
#299 travis ci build status is broken

### PR DESCRIPTION
**Pull request by dmzaytsev**
For #299 
- fixed malformed xsl and broken test

### CODE REVIEW

**Comment by k0r** [comment]
@dmzaytsev it should look like `[100mb] 2015-5-29` make sure there is a space between the data.

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by k0r** [comment]
@dmzaytsev updated response.

**Comment by dmzaytsev** [comment]
@k0r  this screenshot from my local instance
image

**Comment by k0r** [comment]
@dmzaytsev thanks.

**Comment by karato** [comment]
@dmzaytsev Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@krzyk review it

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge it

**Comment by karato** [comment]
@krzyk I added **16 mins** to your account, many thanks for working with the project! The completion time here was 58535560.; you're getting extra minutes here (c=1); +16 added to your rating, current score is: [+4631](http://www.netbout.com/b/35035?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
