### PR TITLE
#214 Documented file and folder sharing

### PR DESCRIPTION
**Pull request by carlosmiranda**
See #214. I wrote this description based on what other services, e.g. Dropbox, Google Drive, OneDrive, offer. Please do make suggestions on how to improve it, I may have missed something.

### CODE REVIEW

**Comment by karato** [comment]
@carlosmiranda Thanks, I will find someone to review this PR soon

**Comment by karato** [comment]
@longtimeago review it

**Comment by longtimeago** [comment]
@karato please merge

**Comment by longtimeago** [comment]
@carlosmiranda thank you! now it become more clear

**Comment by carlosmiranda** [comment]
@longtimeago Updated with some basic implementation stubs as per @yegor256's suggestion.

**Comment by longtimeago** [comment]
@carlosmiranda thank you! Great start

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@carlosmiranda I think you're a bit wrong here. You're mixing together two features, while we should focus only on one of them at this ticket. We should just make files private or public. This has nothing to do with sharing. Sharing is a different feature, which already works. It doesn't require anything else, it works fine as is. We just need a flag for each document: public ON/OFF. That's it.

**Comment by carlosmiranda** [comment]
@yegor256 Right, I got confused because of the word "sharing" in the original ticket. Public/private makes sense now. Let me make changes.

**Comment by carlosmiranda** [comment]
@yegor256 Revisions pushed, please review again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@longtimeago thanks, paid, **19 mins** to your account, payment ID is `56005241`, task took 24 hours and 24 mins to complete... review comments (c=4) added as a bonus... +19 to your rating, your total score is [+4707](http://www.netbout.com/b/35024?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
