### PR TITLE
#19: fixed JSR-303

### PR DESCRIPTION
**Pull request by ggajos**
for #19

### CODE REVIEW

**Comment by karato** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@maurezen do this review

**Comment by maurezen** [comment]
@ggajos a couple of comments above.

**Comment by ggajos** [comment]
@maurezen thanks, please see now

**Comment by maurezen** [comment]
@rultor pls merge

@ggajos thanks, I think it's okay now

**Comment by ggajos** [comment]
@rultor merge please

**Comment by ggajos** [comment]
@rultor merge please

**Comment by karato** [comment]
@rultor deploy now pls

**Comment by karato** [comment]
@maurezen I just added **16 mins** to your account, many thanks for your contribution... you're getting extra minutes here (c=1). +16 added to your rating, current score is: [+1201](http://www.netbout.com/b/35102?open=rating)

**Pull request merged**
