### PR TITLE
#37: added new estimations

### PR DESCRIPTION
**Pull request by ggajos**
for #37

### CODE REVIEW

**Comment by karato** [comment]
Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@carlosmiranda do this review

**Comment by carlosmiranda** [comment]
@rultor Let's merge

**Comment by ggajos** [comment]
@rultor merge

**Comment by karato** [comment]
@carlosmiranda thanks, paid, **16 mins** to your account, payment ID is `52903603`. you're getting extra minutes here (c=1). added +16 to your rating, now it is equal to [+3492](http://www.netbout.com/b/35023?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
