### PR TITLE
#144 Implemented TkAddFriendTest

### PR DESCRIPTION
**Pull request by carlosmiranda**
Implemented a unit test for `TkAddFriend`, as described in #144.

### CODE REVIEW

**Comment by karato** [comment]
Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled paid, thanks, added **16 mins** to your account, payment `54666772`, 14 hours and 28 mins was spent

extra minutes for review comments (c=1)

+16 to your rating, your total score is [+2249](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
