### PR TITLE
#180: added test case

### PR DESCRIPTION
**Pull request by ggajos**
for #180 

Added first test case and modified PDD description.

### CODE REVIEW

**Comment by karato** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@alevohin review it

**Comment by alevohin** [comment]
@karato please assign someone else

**Comment by karato** [comment]
> @karato please assign someone else

@alevohin someone else will help in this task, no problem at all

**Comment by karato** [comment]
@longtimeago do this review

**Comment by longtimeago** [comment]
@rultor merge please

**Comment by yegor256** [comment]
@rultor merge

**Comment by ggajos** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@longtimeago paid, thanks, added **16 mins** to your account, payment `55121293`, 21 hours and 41 mins was spent; you're getting extra minutes here (c=1); +16 added to your rating, current score is: [+3909](http://www.netbout.com/b/35024?open=rating)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
