### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
updated.

### CODE REVIEW

**Comment by yegor256** [comment]
@k0r keep in mind that README is not a marketing document. It can't contain any ambiguities, like "& more". This document is used by the technical team to understand what to do. "& more" is rather confusing :) I would suggest to put back the list of features we had and add a marketing explanation, if you want, as a separate paragraph.

**Comment by karato** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by karato** [comment]
@krzyk do this review

**Comment by krzyk** [comment]
@k0r besides @yegor256 comments, README.md has been changed on master, you merge is required

**Comment by yegor256** [comment]
I think this pull request is outdated and won't be merged. Besides that, it removes an important part of the README document that describes the scope of the product. I'm closing it

**Comment by karato** [comment]
@krzyk **16 mins** added to your account (payment number `54196404`), many thanks for your contribution! 330 hours and 12 mins spent here.

review comments (c=1) added as a bonus

+16 to your rating, your total score is [+5272](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
