### PR TITLE
#34: updated travis build

### PR DESCRIPTION
**Pull request by ggajos**
for #34

### CODE REVIEW

**Comment by karato** [comment]
Thanks, I will ask someone to do a code review here, thanks for your pull request

**Comment by karato** [comment]
@longtimeago review it

**Comment by longtimeago** [comment]
@ggajos that's fine, but where is cobertura profile itself?

**Comment by ggajos** [comment]
@longtimeago thanks, thought that cobertura is part of jcabi parent, please see now

**Comment by longtimeago** [comment]
@ggajos unfortunately, not yet. Lat's wait for while for the travis build. You may need to exclude some classes and added todos to fix code coverage :)

**Comment by longtimeago** [comment]
@ggajos works fine, cool!

**Comment by longtimeago** [comment]
@rultor good to merge

**Comment by longtimeago** [comment]
@ggajos hehe ... we have another PR for cobertura profile https://github.com/teamed/nerodesk/pull/35

**Comment by ggajos** [comment]
@rultor merge

**Comment by karato** [comment]
@rultor please deploy

**Comment by karato** [comment]
@longtimeago **20 mins** added to your account (payment number `52905046`), many thanks for your contribution!... you're getting extra minutes here (c=5)... +20 added to your rating, at the moment it is: [+2781](http://www.netbout.com/b/35024?open=rating)

**Pull request merged**
