### PR TITLE
#179: Changed input so guessing logic can recognize file type correctly

### PR DESCRIPTION
**Pull request by ggajos**
for #179:

Changed input so guessing logic can recognize file type correctly.

### CODE REVIEW

**Comment by karato** [comment]
Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@caarlos0 do this review

**Comment by caarlos0** [comment]
I got your branch here. It didn't work:

```
Failed tests:
  MkDocTest.guessesContentType:155
Expected: "text/plain"
     but: was null

Tests in error:
  TkDocsTest.returnsListOfDocs:63 » ConstraintViolation content can't be NULL
```

**Comment by ggajos** [comment]
@caarlos0 hmm, that's wierd, is working on my machine, need to double check

**Comment by ggajos** [comment]
@caarlos0 hmm, any hint, CI is working and those tests are working on my machine also. Any ideas how I can break it? Moreover this test `TkDocsTest.returnsListOfDocs` is not related with my change.

**Comment by caarlos0** [comment]
@ggajos Don't know...

Which OS are you using? I'm using Mac OS X, might be related...

**Comment by ggajos** [comment]
@caarlos0 I'm out of ideas here, @yegor256 how we should proceed? Should I give this ticket to somebody else?

**Comment by yegor256** [comment]
@ggajos I have no idea. it also crashes on my Mac. there is something wrong with MIME type detection on Java-with-Mac. I don't know... I just made a workaround in the code... it's already in master branch

**Comment by caarlos0** [comment]
Maybe an assumption for os != mac?

**Comment by ggajos** [comment]
my workaround doesn't make sense as it's working only on Win.

**Comment by karato** [comment]
@caarlos0 Thank you, I have added **18 mins** to your account in payment/transaction "`AP-2LR52517VG354631A`", time consumed: 45 hours and 48 mins. you're getting extra minutes here (c=3). +18 to your rating, your total score is [+1600](http://www.netbout.com/b/35095?open=rating)

**Pull request closed without merging**
