### PR TITLE
#96 increased branch coverage

### PR DESCRIPTION
**Pull request by krzyk**

### CODE REVIEW

**Comment by karato** [comment]
Thanks for your pull request, let me find someone who can review it

**Comment by karato** [comment]
@carlosmiranda review it

**Comment by carlosmiranda** [comment]
@rultor looks good to merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by karato** [comment]
@carlosmiranda Thank you, I have added **16 mins** to your account in payment/transaction "`54092969`". extra minutes for review comments (c=1). added +16 to your rating, now it is equal to [+4058](http://www.netbout.com/b/35023?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
