### PR TITLE
#42: updated how to contribute section

### PR DESCRIPTION
**Pull request by ggajos**
for #42

### CODE REVIEW

**Comment by karato** [comment]
Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@alevohin do this review

**Comment by alevohin** [comment]
@rultor merge

**Comment by alevohin** [comment]
@ggajos please confirm merge

**Comment by ggajos** [comment]
@rultor merge

**Comment by karato** [comment]
@alevohin **17 mins** was added to your account, many thanks for your contribution!; extra minutes for review comments (c=2); +17 added to your rating, current score is: [+1372](http://www.netbout.com/b/35105?open=rating)

**Comment by karato** [comment]
@rultor deploy

**Pull request merged**
