### PR TITLE
#274 fix NPE

### PR DESCRIPTION
**Pull request by dmzaytsev**

### CODE REVIEW

**Comment by dmzaytsev** [comment]
@rultor merge

**Comment by k0r** [comment]
@dmzaytsev Travis CI error.

**Comment by dmzaytsev** [comment]
@k0r just not complete

**Comment by yegor256** [comment]
@k0r it's a very bad practice to merge directly into master without Rultor. please, stop doing this

**Comment by dmzaytsev** [comment]
@yegor256 I did push one more commit
but I can't see it

**Comment by karato** [comment]
@dmzaytsev Thanks for the pull request, let me find a reviewer..

**Comment by dmzaytsev** [comment]
@yegor256 this https://github.com/dmzaytsev/nerodesk/commit/7ae008399784dfcab6553c4c9dd783c3e63c9959

**Comment by yegor256** [comment]
@dmzaytsev that's because @k0r merged your branch already into master, without rultor and code review :(

**Comment by dmzaytsev** [comment]
@yegor256 any idea how to fix it ?

**Comment by karato** [comment]
@krzyk review it

**Comment by dmzaytsev** [comment]
@yegor256 maybe  create a new branch ?

**Comment by dmzaytsev** [comment]
@yegor256 anyway we can release now
NPE should be disappear
but date will be empty

**Comment by yegor256** [comment]
@dmzaytsev yes, they only solution is to create a new branch and a new pull request

**Comment by k0r** [comment]
@yegor256 `master` is deprecated?

**Comment by yegor256** [comment]
@k0r what do you mean?

**Comment by dmzaytsev** [comment]
I create new PR #295

**Comment by karato** [comment]
@krzyk I don't see any messages from you above, not sure if there was actual contribution (correct me if I'm wrong)

**Comment by karato** [comment]
@rultor deploy pls

**Pull request merged**
