### PR TITLE
#133 Redirect to root on bad request

### PR DESCRIPTION
**Pull request by longtimeago**

### CODE REVIEW

**Comment by longtimeago** [comment]
@karato please find someone for review

**Comment by karato** [comment]
Let me find a reviewer for this pull request, thanks for submitting it

**Comment by karato** [comment]
@krzyk review it

**Comment by krzyk** [comment]
@longtimeago please merge master

**Comment by karato** [comment]
@krzyk **16 mins** sent to your balance (ID `54256938`), many thanks! It took 27 hours and 11 mins.; you're getting extra minutes here (c=1); added +16 to your rating, now it is equal to [+5466](http://www.netbout.com/b/35035?open=rating)

**Pull request closed without merging**
