### PR TITLE
#37: fixed pdd typo

### PR DESCRIPTION
**Pull request by ggajos**
for #37

### CODE REVIEW

**Comment by karato** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@darkled review it

**Comment by asaen** [comment]
@rultor merge

**Comment by ggajos** [comment]
@rultor merge

**Comment by ggajos** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled thanks, paid, **16 mins** to your account, payment ID is `52967509`. you're getting extra minutes here (c=1). +16 added to your rating, current score is: [+1830](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
