### PR TITLE
#46 Installation order changed

### PR DESCRIPTION
**Pull request by longtimeago**
Small fix related to #46 for the software installation order
@ggajos @alevohin Please, just merge asap

### CODE REVIEW

**Comment by karato** [comment]
Thanks, someone will review your pull request soon

**Comment by karato** [comment]
@caarlos0 do this review

**Comment by caarlos0** [comment]
@rultor good to merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by longtimeago** [comment]
@yegor256 looks like we need to put these changes to master directly.

**Comment by yegor256** [comment]
@longtimeago done in 3b78215

**Comment by longtimeago** [comment]
@yegor256 thank you!

**Comment by caarlos0** [comment]
@longtimeago seems you need to merge with master

**Comment by longtimeago** [comment]
It's alreade merged by @yegor256 so just closing it. Thanks

**Comment by karato** [comment]
@caarlos0 Thank you, I have added **17 mins** to your account in payment/transaction "`AP-39E14559SJ300141S`"; review comments (c=2) added as a bonus; added +17 to your rating, now it is equal to [+1187](http://www.netbout.com/b/35095?open=rating)

**Pull request closed without merging**
