### PR TITLE
#215 upgrade of takes and enabling tests

### PR DESCRIPTION
**Pull request by krzyk**
#215

Upgrade to takes 0.13.1 and enabled tests for invalid filenames (which were fixed in takes 0.13.1)

### CODE REVIEW

**Comment by karato** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by karato** [comment]
@darkled do this review

**Comment by asaen** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled we're on pause in the project, please stop working with this, until further information

**Comment by karato** [comment]
@darkled we're not on pause any more, you may continue to work with the task

**Comment by asaen** [comment]
@krzyk there are some merge conflicts, please resolve them

**Comment by krzyk** [comment]
@darkled merged, please check

**Comment by asaen** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled I added **18 mins** to your account, many thanks for working with the project! The completion time here was 55963233.... review comments (c=3) added as a bonus... +18 added to your rating, at the moment it is: [+2277](http://www.netbout.com/b/35091?open=rating)

**Comment by karato** [comment]
@rultor please deploy

**Pull request merged**
