### PR TITLE
added .pdd config file

### PR DESCRIPTION
**Pull request by ggajos**

### CODE REVIEW

**Comment by ggajos** [comment]
@rultor merge

**Comment by ggajos** [comment]
@yegor256 can I add me to .rultor.yml? and we can merge this along with .pdd fix? On the other hand I see that I'm mentioned there. created #24

**Comment by karato** [comment]
@darkled do this review

**Comment by yegor256** [comment]
@ggajos try again, should work

**Comment by ggajos** [comment]
@rultor merge

**Comment by karato** [comment]
@darkled there weren't any messages from you, no need to pay, as I understand (feel free to correct me)

**Comment by karato** [comment]
@rultor please deploy

**Comment by asaen** [comment]
@karato right

**Pull request merged**
